[package]
name = "stake-contract"
version = "0.7.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-bls12_381 = { version = "0.12", default-features = false, features = ["rkyv-impl"] }
dusk-bls12_381-sign = { version = "0.5", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"
dusk-jubjub = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
dusk-pki = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
dusk-plonk = { version = "0.16", default-features = false, features = ["rkyv-impl", "alloc"] }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
transfer-contract-types = { version = "0.1.0", path = "../transfer-types", default-features = false }
stake-contract-types = { version = "0.0.1-rc.2", path = "../stake-types", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
rusk-abi = { version = "0.12.0-rc", path = "../../rusk-abi" }

[dev-dependencies]
rusk-profile = { version = "0.6", path = "../../rusk-profile" }
phoenix-core = { version = "0.21", default-features = false, features = ["rkyv-impl", "alloc"] }
rusk-abi = { version = "0.12.0-rc", path = "../../rusk-abi", default-features = false, features = ["host"] }
transfer-circuits = { version = "0.5", path = "../../circuits/transfer" }
rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
hex = "0.4"
rand = "0.8"
poseidon-merkle = { version = "0.3", features = ["rkyv-impl"] }
ff = { version = "0.13", default-features = false }
criterion = "0.4"

[[bench]]
name = "get_provisioners"
harness = false
